apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      # Use host aliases for local development
      # hostAliases:
      # - ip: "172.20.80.1"
      #   hostnames:
      #   - "keycloak.127.0.0.1.nip.io"
      containers:
      - name: server
        image: kennethreitz/httpbin
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        env:
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://localhost"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "server"
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: "d1680bbb-24f3-4835-a0d9-2a7492a4cc99"
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: "MTExMTExMTExMTExMTExMQ=="
        - name: OAUTH2_PROXY_COOKIE_REFRESH
          value: "5m"
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: "false"
        # Optional:
        # - name: OAUTH2_PROXY_REDIRECT_URL
        #   value: "http://localhost:8000/oauth2/callback"
        # - name: OAUTH2_PROXY_WHITELIST_DOMAINS
        #   value: "keycloak.127.0.0.1.nip.io:*"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          # Provide public FQDN of IdP reacheable by the proxy and public client
          value: http://d674-180-129-106-95.ngrok.io/auth/realms/dev
        args:
        - "--email-domain=*"
        - "--skip-provider-button=true"
        - "--provider=oidc"
        - "--insecure-oidc-allow-unverified-email=true"
        - "--http-address=0.0.0.0:4180"
        ports:
        - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  selector:
    app: server
  ports:
  - port: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sidecar-ingress
spec:
  rules:
  - host: sidecar.127.0.0.1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: server-svc
            port:
              number: 4180
